### ISSUE TITLE
Odd issue with underline in non-monospace apps

### ISSUE THREAD

**Issue by Akselmo** [eigilnikolajsen/commit-mono#10]
Hey, I don't know if this is a font thing or app thing, but felt like asking..

I like using this font everywhere, basically. It's great, helps me read things.

However, seems in non-monospace fields, the underlining behaves a bit oddly. Like it's a bit squashed on top of the text?

In the screenshot, above text is in Konsole, KDE terminal app.
The text below is in Nheko, a Qt chat application for Matrix.

![image](https://github.com/eigilnikolajsen/commit-mono/assets/13801236/e372e34e-afd6-45a7-ba85-44dc3c2ddd01)

Seems the bug is also apparent in Kate, KDE code editor:

![image](https://github.com/eigilnikolajsen/commit-mono/assets/13801236/3c3117ec-5243-4a8f-8d79-b81d4ecd3066)

It seems the gap between underline and the text is gone in some applications.

I am using the otf fonts from the dev packages, only things I've customized are `alt-g` and `square-dots`.

I don't know if this is a font thing or linux thing or Qt thing... But all apps I screenshotted use Qt, so I am not sure.

My system info:

```
Operating System: Arch Linux 
KDE Plasma Version: 5.27.6
KDE Frameworks Version: 5.108.0
Qt Version: 5.15.10
Kernel Version: 6.4.3-arch1-1 (64-bit)
Graphics Platform: Wayland
Processors: 12 × AMD Ryzen 5 3600 6-Core Processor
Memory: 15.5 GiB of RAM
Graphics Processor: AMD Radeon RX 6600
```

Is there anything I could help to do to track this down? Again, I really love this font, it made my reading experience much easier everywhere, and having the ability to use single-storey-g is great.

Alternatively, non-monospace version of this font for use in system wide applications that do not expect to use monospace fonts would be great! I think that may fix the issue, but not sure.

**Comment by eigilnikolajsen** [comment]
Interesting. I have an idea to why it is looking weird - I will try to fix.

**Comment by Akselmo** [comment]
Hi, any updates on this? :)

**Comment by eigilnikolajsen** [comment]
Will work on it, when I have time.

**Comment by eigilnikolajsen** [comment]
@Akselmo will you check if this is fixed with the latest version, that I just shipped?

**Comment by Akselmo** [comment]
![image](https://github.com/eigilnikolajsen/commit-mono/assets/13801236/d75ff7fd-9683-475b-a20b-c61d403a97d5)

Yeah, looks better now, it's not underlining the bottom dot in the `:` like previously.

**Comment by rben01** [comment]
Just another datapoint, here is underline in macOS Terminal. Looks fine.
<img width="177" alt="image" src="https://github.com/eigilnikolajsen/commit-mono/assets/766670/fc5485bc-a29e-4da9-a67e-f5d6499e0336">

**Comment by Akselmo** [comment]
Seems font size affects a bit to the underline position. On font size 11 it looks fine, but on 10 it still gets a bit too close to the bottom dot in `:`.

Also something interesting I found.. In libreoffice if I tried to underline the font, it did not show up at all

![image](https://github.com/eigilnikolajsen/commit-mono/assets/13801236/d1c7c826-10c5-44ac-b995-462c5f3648e7)

Attached the odt file just if you want to give it a try as well
[commitmonotest.odt](https://github.com/eigilnikolajsen/commit-mono/files/12207182/commitmonotest.odt)

**Comment by eigilnikolajsen** [comment]
I don't know where to go with this issue, can I close it?

**Comment by Akselmo** [comment]
> I don't know where to go with this issue, can I close it?

Fine by me!
