### ISSUE TITLE
Alternate variant for "r"

### ISSUE THREAD

**Issue by kaushikgopal** [eigilnikolajsen/commit-mono#106]
I recently discovered CommitMono.I just want to say thank you! I absolutely love this font and have it as my daily driver. I especially appreciate how customizable you've made it. I've tested numerous variants and found just the one i really like.

Would you by any chance consider a customization for the alphabet "r" which has an extender at the baseline? (similar to the variant of "i" that you have).

I don't have a way of articulating my reason well but i'll try - for some reason the "r" feels _way_ too simple, so as to cause some imbalance in how overall text, or code reads. I've noticed other commendable fonts you referenced, do have a base extender at the bottom and for some reason makes it feel more "balanced" and doesn't stand out on its own. You do provide a similar option for the character "i" so i'm wondering if similar reasoning could apply.

Of course, you know what's right and if it even makes sense, but just thought i'll shoot the ask anyway.Thanks again for the wonderful work!

**Comment by eigilnikolajsen** [comment]
Thank you for your comment. This will be added in the next version as it has already been filed in #83

**Comment by kaushikgopal** [comment]
i thought i searched the issues, but clearly did a terribly poor job. even #83's title is similar. 🙇‍♂️ super excited about this. closing this issue as a duplicate.

🙏 thank you for the wonderful work.
