### ISSUE TITLE
Extending Char set to support Table and Flowchart drawing in ASCII art

### ISSUE THREAD

**Issue by ali10129** [eigilnikolajsen/commit-mono#108]
I understand that you are doing an excellent job maintaining the CommitMono font, and I truly appreciate your efforts.

If it is not too much trouble, please consider extending the ASCII table to support additional characters such as ||- -|| and others commonly used in ASCII art. ( last two rows in [Courier Charmap from wiki](https://upload.wikimedia.org/wikipedia/commons/9/9b/IBMCourierCharmap.svg) )
This would enable people like me to use your font not only for coding but also for drawing old-fashioned tables and flowcharts in ASCII art.

Your effort would be greatly appreciated.

**Comment by eigilnikolajsen** [comment]
These characters are already in the font. ![Screenshot_20240526-090621.png](https://github.com/eigilnikolajsen/commit-mono/assets/71004327/222789e5-88c7-4a7c-b139-fca7ba3fe018)
