### ISSUE TITLE
Website contrast accessiblity issue

### ISSUE THREAD

**Issue by Akselmo** [eigilnikolajsen/commit-mono#11]
I didn't want to join the other issue with dumb name, so I made my own for this.

Anyway, the website is really cool, but I think the black on gray or gray on black does not have enough contrast between them.

I am the type that needs high-contrast themes to read things easier, or my eyes tire out fast. I like the aesthetic you are going for, but for contrast issues, maybe white-on-black and black-on-white would work better?

Again your website, I'm not here to demand anything, could have a "high-contrast" toggle button maybe :) Just a thought!

**Comment by eigilnikolajsen** [comment]
Good idea about adding a toggle button, I'll look into it!

**Comment by eigilnikolajsen** [comment]
@Akselmo I have added a toggle on the latest version of the site. Use key C to toggle high contrast mode.

**Comment by Akselmo** [comment]
Brilliant, works well! Thanks :)
