### ISSUE TITLE
[enhancement request] add the www ligature

### ISSUE THREAD

**Issue by teotimepacreau** [eigilnikolajsen/commit-mono#110]
here an example in Space Mono ligature edition ![image](https://github.com/eigilnikolajsen/commit-mono/assets/95431443/bb288fad-0fba-469f-b9b8-a3f7441dbae8)

**Comment by eigilnikolajsen** [comment]
What purpose does this serve? If it's only an aesthetic one, it won't be included.

**Comment by Secret-chest** [comment]
> lisibility ?

But regular `www` is legible. This is the ligature I least understand, are we turning www into a logo?
