### ISSUE TITLE
Ligatures not working in none of the editors or terminals

### ISSUE THREAD

**Issue by assayire** [eigilnikolajsen/commit-mono#111]
I downloaded commit mono from the website using the following settings:

```json
{
  "weight": 400,
  "italic": false,
  "alternates":
  {
    "cv01": false,
    "cv02": false,
    "cv03": false,
    "cv04": false,
    "cv05": true,
    "cv06": true,
    "cv07": false,
    "cv08": false,
    "cv09": false,
    "cv10": false,
    "cv11": true
  },
  "features":
  {
    "ss01": true,
    "ss02": true,
    "ss03": true,
    "ss04": true,
    "ss05": true
  },
  "letterSpacing": 0,
  "lineHeight": 1.25
}
```

I have tried using it in 
- editors - sublime text, zed, vs code, intellij etc., 
- terminals - iterm, warp, mac terminal etc. 

I can't seem to get the ligatures working. By ligatures i mean arrows and equals like the following (Fira Code sample):

<img width="222" alt="image" src="https://github.com/eigilnikolajsen/commit-mono/assets/66568479/ab28e256-b23c-4bae-8dcb-6c7b85453a8a">

What am I missing?

---

I am on 
- MacOS Sonoma 14.5
- Commit Mono v143 (per download)

Snapshot shot of my customizations on the website.
![image](https://github.com/eigilnikolajsen/commit-mono/assets/66568479/07398941-be57-44cc-baa6-5cc877e096f1)

**Comment by eigilnikolajsen** [comment]
Looks like you downloaded the package "for design". This package contains variable fonts as well. What fonts did you install on your system?

**Comment by assayire** [comment]
Yes, I downloaded the design one because it listed `ssxx` features. I installed the variable ttf on my system.

Also, I downloaded and installed the fonts with default settings on the install tab. They also don’t show any ligatures.

**Comment by eigilnikolajsen** [comment]
![Screenshot_20240706-210204.png](https://github.com/eigilnikolajsen/commit-mono/assets/71004327/47b7c4fa-df20-4909-be3f-355d87f8c23f)

As also stated here, the variable files don't contain the custom settings, which is why they're listed, so you can input them in your editor:)

**Comment by assayire** [comment]
Oops ... I can't believe I missed that. All good now. Thanks.
