### ISSUE TITLE
Website says there is no .woff2, but there is

### ISSUE THREAD

**Issue by rben01** [eigilnikolajsen/commit-mono#12]
> Is there a .woff2 version of the font available?
> No, but you can use an online conversion tool like [this one from Font Squirrel](https://www.fontsquirrel.com/tools/webfont-generator).

(From [here](https://github.com/eigilnikolajsen/commit-mono/blob/61093375b8a94266fe2ae1bd682fb299b2a4aaf9/index.html#L793C80-L793C80))

When I download the zip, there _is_ a .woff2 included, `CommitMono VariableFont.woff2`.

**Comment by eigilnikolajsen** [comment]
That is true, however, the customized static fonts are not available as woff2, only the variable font. I will update it to be more precise. Thank you.

**Comment by eigilnikolajsen** [comment]
I have updated the documentation.
