### ISSUE TITLE
Document character variants and stylistic sets

### ISSUE THREAD

**Issue by rben01** [eigilnikolajsen/commit-mono#13]
It's awesome that Commit Mono has character variants and stylistic sets, so that you don't need to use the website to customize a download. It'd be even better if they were documented on the website, and if it were indicated that customizations only affect the single-font download.

**Comment by eigilnikolajsen** [comment]
I will update the docs to include the actual features, so you can use the variable font on the web for example.

**Comment by eigilnikolajsen** [comment]
I have updated documentation to include the feature tags so you can use the variable more flexibly.
