### ISSUE TITLE
Large vertical gaps between box drawing characters

### ISSUE THREAD

**Issue by rben01** [eigilnikolajsen/commit-mono#16]
```text
┌┬┐╔╦╗
├┼┤╠╬╣
└┴┘╚╩╝
```

Commit Mono renders as:

<img width="58" alt="image" src="https://github.com/eigilnikolajsen/commit-mono/assets/766670/9bc1dccf-bab1-45a3-bacb-f68059cda5f5">

It would be nice to tighten up those vertical gaps (without needing to decrease line height).

Examples of other fonts:

- PT Mono
     <img width="52" alt="image" src="https://github.com/eigilnikolajsen/commit-mono/assets/766670/ad644900-4198-4ed8-8532-5ceeb612e5bb">
- Courier New
    <img width="54" alt="image" src="https://github.com/eigilnikolajsen/commit-mono/assets/766670/43086917-e405-4fca-b2b6-17673661db33">
- Iosevka
     <img width="44" alt="image" src="https://github.com/eigilnikolajsen/commit-mono/assets/766670/84450bf6-8ffb-4cc8-9037-1d832e5acfe5">

**Comment by eigilnikolajsen** [comment]
Great spot, I'll look into it!

**Comment by rben01** [comment]
Actually in seems to depend on the editor and the font weight?

In CotEditor.app, it only happens at font weight 450. In TextEdit, it happens at all font weights. In VSCode, a line spacing of 1 fixes the issue but then causes the lines to be too close together to read easily.

**Comment by eigilnikolajsen** [comment]
Yes, I think I just need to make them taller. This might cause some small pixel overlap issues but much better than being disconnected.

**Comment by eigilnikolajsen** [comment]
This should be fixed in version 1.132.
