### ISSUE TITLE
Zip file on web site is corrupted

### ISSUE THREAD

**Issue by rossburton** [eigilnikolajsen/commit-mono#17]
If I download the zip file on the web site (I can't give you the URL as it's buried in javascript), it won't decompress properly:

```
$ unzip CommitMono.zip
Archive:  CommitMono.zip
  inflating: CommitMono-450-Regular.otf
  inflating: CommitMono-450-Italic.otf
  error:  invalid compressed data to inflate
  inflating: CommitMono-700-Regular.otf
  inflating: CommitMono-700-Italic.otf
  error:  invalid compressed data to inflate
  inflating: installation.txt
  inflating: license.txt
```

The zip on the GitHub releases page works fine.

**Comment by eigilnikolajsen** [comment]
Yes, I am aware of this. To my knowledge this issue only occurs when downloading from Safari.

**Comment by eigilnikolajsen** [comment]
I can't get the safari download to work so I just blocked it off completely.
