### ISSUE TITLE
Stylistic set with programming ligatures not surrounded by space

### ISSUE THREAD

**Issue by henryso** [eigilnikolajsen/commit-mono#18]
I have noticed that some terminal emulators (notably kitty and wezterm) don't include surrounding spaces when determining glyph substitutions, so the programming ligatures (ss02) are never triggered. Another related issue is when some sequence occurs at the end of a line.

Would it be possible to have an alternate stylistic set that doesn't require the surrounding spaces for the glyph substitution to occurs?

**Comment by eigilnikolajsen** [comment]
I will not pursue this.

**Comment by henryso** [comment]
Whatever you've done since I posted this has fixed the problem that caused me to post this.  Thanks!
