### ISSUE TITLE
alternative i

### ISSUE THREAD

**Issue by voladelta** [eigilnikolajsen/commit-mono#21]
Eigil,
thank you for making the font, it's beautiful 
> first time i have to make the donation because you deserve

so i open the issue from your suggestion from the mail

current i interrupts the reading flow

for example 
<img width="208" alt="image" src="https://github.com/eigilnikolajsen/commit-mono/assets/91018286/9eaf3092-a6f9-4465-ac7b-476b3eb95780">

it would be great if we have something like first 2s here (sorry for bad drawing with mouse 😅)

<img width="622" alt="image" src="https://github.com/eigilnikolajsen/commit-mono/assets/91018286/7e4c9c54-1fae-4e59-83ce-0dbe9a787468">

> take your time, just a suggestion

**Comment by eigilnikolajsen** [comment]
Thank you for your kind words.
A question: Are you proposing to 1. Make a ligature that substitutes the `i` for a different `i` when it appears in combinations like `li` or `ti` or 2. Make a global alternate `i` that doesn't have a left bottom serif for example?

**Comment by voladelta** [comment]
> Make a global alternate i that doesn't have a left bottom serif for example?
This one would be better 😄, since it would be weird to see different i at different place/combination (as 1).

**Comment by eigilnikolajsen** [comment]
Okay, gotcha.

**Comment by eigilnikolajsen** [comment]
Hello, I tried to add an alternate 'i' with a tail like the 'l'. But it simply didn't look good. Instead I added an alternate 'i' without serifs altogether, which you can try in the latest version from [commitmono.com](https://commitmono.com/).
