### ISSUE TITLE
Bug: ◑ and ◐ are rendered the same 

### ISSUE THREAD

**Issue by rben01** [eigilnikolajsen/commit-mono#22]
Commit Mono renders the characters ◑ and ◐ as the same character, ◐.

Input:
```
julia> collect("◑ ◐")
3-element Vector{Char}:
 '◑': Unicode U+25D1 (category So: Symbol, other)
 ' ': ASCII/Unicode U+0020 (category Zs: Separator, space)
 '◐': Unicode U+25D0 (category So: Symbol, other)
```

Rendered:
<img width="480" alt="image" src="https://github.com/eigilnikolajsen/commit-mono/assets/766670/8e10bea3-24fb-4420-b00f-c8059fc31873">

**Comment by eigilnikolajsen** [comment]
Nice spot! I'll fix it asap.

**Comment by rben01** [comment]
Thanks! I thought I was losing my mind watching a unicode spinner rotate back and forth 180° instead of around and around 360° 😄

**Comment by eigilnikolajsen** [comment]
Fixed in latest version!
