### ISSUE TITLE
Slanted 'g' is not installed/displayed properly on macOS.

### ISSUE THREAD

**Issue by babelthe** [eigilnikolajsen/commit-mono#25]
First of all, thanks for creating/sharing such a high-quality dedicated work!❣️

Here is some quirky behavior I found in macOS.

## Configuration
![image](https://github.com/eigilnikolajsen/commit-mono/assets/140987369/aef5b4f7-c83f-4315-9f62-d9f14e907540)

## Desired Outcome 
This is what I want and it seems working fine in the site.
![image](https://github.com/eigilnikolajsen/commit-mono/assets/140987369/7a3e9ea8-752a-4e45-ac47-d9a3239bfb84)

And quicklook of downloaded files:
![Screenshot 2023-08-06 at 10 58 52](https://github.com/eigilnikolajsen/commit-mono/assets/140987369/9bf039cd-2542-4e12-8a36-a012e40ec054)
![Screenshot 2023-08-06 at 10 58 16](https://github.com/eigilnikolajsen/commit-mono/assets/140987369/b034f3b9-a3b4-4e84-abfe-69e382b71753)

## Problem
However, when I install this customized fonts, only italic 'g' is not showing correctly in Font Book.app.
![Screenshot 2023-08-06 at 10 59 43](https://github.com/eigilnikolajsen/commit-mono/assets/140987369/07acd5cd-b9f2-4ef7-abcf-ebae80f2f381)
![Screenshot 2023-08-06 at 10 59 48](https://github.com/eigilnikolajsen/commit-mono/assets/140987369/9a05bcc6-a4dc-4ba4-912d-0d1be0129add)

Here is what happen in actual use:
![94aa4c017406f61e8b3a94d3478dcbfb4955dde3db6cc2f9ed14b06c73384729](https://github.com/eigilnikolajsen/commit-mono/assets/140987369/a71cbb0f-d383-4e13-8d1c-1ec5cc20044d)
![6fab10f73899b30765f6dcc78a11937d4eb8dbc24a3e942f507eaf1b56f2ef7f](https://github.com/eigilnikolajsen/commit-mono/assets/140987369/e87c8fb8-420d-42d7-be11-f29b8063943a)
![15573e1b22877473ac3f7895511d725b77a9ac5a1dba2e1bae85e52a2e380b8f](https://github.com/eigilnikolajsen/commit-mono/assets/140987369/1d3bf232-00c0-45b1-969b-4c8a53af56c8)

I checked only VSC, Adobe Ai, and Figma.
In those apps display wrong 'g' both regular and italic.
Tried uninstall and reinstall the fonts and restart mac/app.

**P.S.**
Not quite sure what the "Alt. Slanted 'ag'" option does, but I wish I could have separate options for 'a' and 'g'!

**Comment by eigilnikolajsen** [comment]
Okay, some explanation coming up. Firstly I refer to the different `g` with their typographic terminology. The simple `g` is called single storey and the complex one is called double storey. Same with the `a`. 
You want the single storey `g` so you should not check the option `slanted 'ag'`. 
The fonts default behaviour is to use double storey versions in the regular and use single storey in the italic. The option to use `slanted 'ag'` means that both the regular and italic will use double storey constructions. So when you check both the latter will overrule so you get double storey `g` instead.
I'm sorry for the long-winded explanation, I hope you understand?

**Comment by babelthe** [comment]
Thanks for the explanation!
So the thing is, if I uncheck the "slanted 'ag'", now the italic 'a' becomes single-storey. Only regular 'a' being double-storey. Both on the site preview and the apps.
![image](https://github.com/eigilnikolajsen/commit-mono/assets/140987369/9121e2a5-5f0f-4e60-a409-db79a76346cc)



Simply there is no options for this now?
![image](https://user-images.githubusercontent.com/140987369/258616055-7a3e9ea8-752a-4e45-ac47-d9a3239bfb84.png)

I was just expecting that the site preview shows is what I get.

**Comment by eigilnikolajsen** [comment]
Okay, I think I might change it so you have seperate options for a and g, so you can have the option you wish for.

**Comment by eigilnikolajsen** [comment]
Hello I updated the fonts default behaviour to not include alternate versions of 'a' and 'g' in italic. The default italic version is now just slanted versions. This means that you can get your desired result of 'ag' by downloading a custom version from [commitmono.com](https://commitmono.com/) with simply only the option `Alt. 'g'` turned on. Thank you!
