### ISSUE TITLE
Smart kerning doesn't work in Visual Studio Code.

### ISSUE THREAD

**Issue by babelthe** [eigilnikolajsen/commit-mono#26]
Not sure if this is just because VSC doesn't support smart kerning fonts.
![ef247c412db37f845aa2a1a52d3346bb3ffc36bb3a7273686aedfb659a6f10f1](https://github.com/eigilnikolajsen/commit-mono/assets/140987369/da2cc6f6-b219-4d62-9c19-24290629d613)

Looks great in Adobe Illustrator.
![c58abdde4ae5f83550a007d2451d182a1ab8eb18ac87bd641c275ded41d3b993](https://github.com/eigilnikolajsen/commit-mono/assets/140987369/cce77d41-e3ef-4262-9070-1f701fe800ca)

**Comment by eigilnikolajsen** [comment]
Do you have these two lines in the settings.json file?
![Screenshot_20230805-225158](https://github.com/eigilnikolajsen/commit-mono/assets/71004327/ed2b55e5-0dc8-480f-b021-e8b3d9c6d684)

**Comment by babelthe** [comment]
That is what I was missing!
`"terminal.fontLigatures": true`

Thank you <3
