### ISSUE TITLE
Regular renders as bold in some apps

### ISSUE THREAD

**Issue by elshize** [eigilnikolajsen/commit-mono#27]
Hi, first off, fantastic work on the font. I really like both the philosophy and the end product.

I've noticed that some apps render the regular font (I tried anything between 400 and 500) in bold.

For example, here is the rendering in kitty terminal:

![image](https://github.com/eigilnikolajsen/commit-mono/assets/3026120/aa60fbeb-d429-44a9-8a5b-a194b3088010)

And here it is in Foot:

![image](https://github.com/eigilnikolajsen/commit-mono/assets/3026120/71667f32-7582-4c96-8045-97d3a12093d4)

It's also not necessarily consistent within a single app...

I have honestly no idea if this is in any way related to the font itself, but it doesn't happen to other fonts, so I'm wondering if there's some setting in the font that may be causing it... Or alternatively, if anyone has an idea what I might try tweaking on my side.

I downloaded the "dev" fonts from the website.

I'm on Fedora 38 and Wayland compositor (if that means anything to anyone and  makes any different).

Thanks again for a great font!

**Comment by eigilnikolajsen** [comment]
To my eye - from the attached screenshots - it doesn't look bold. The bolder version is a lot bolder than in the screenshots.
However, it does look like the antialiasing might differ across the apps, so maybe there is some in-app settings which can change font rendering (antialiasing or hinting).

**Comment by elshize** [comment]
Thanks, I'll look into anti-aliasing settings.

**Comment by elshize** [comment]
Seems like it may be related to _stem darkening_ https://bugreports.qt.io/browse/QTBUG-95336 

Setting `FREETYPE_PROPERTIES=cff:darkening-parameters=0,0,0,0,0,0,0,0` fixes it for QT5 apps, still working on finding solutions for others.

Will report shortly.

**Comment by eigilnikolajsen** [comment]
Interesting, those parameters look awfully much like PANOSE numbers, which is font specific system for classification using 8 numerical values. I did add the correct PANOSE identifier to the most [recent release](https://github.com/eigilnikolajsen/commit-mono/releases/tag/1.132). However, can I have you try the first version (where I think the PANOSE number is neutral), if it's not too much hassle? Would be a big help, because then I can fix for the next release!

**Comment by elshize** [comment]
Just tried it, no change. I found some background on this feature: https://freetype.org/freetype2/docs/hinting/text-rendering-general.html#experimental-stem-darkening-for-the-auto-hinter

I suppose it's not good or bad, rather some apps/frameworks decide to use it by default, while others don't. Seems like it's implemented to hide some shortcomings in other rendering features.

What is annoying is that it seems that my browser (Qutebrowser, which is QT5, using blink engine underneath), uses different options for UI and different for rendered web pages :shrug: But anyway, the issue seems to be due to freetype settings.

Let me know if there's anything else you'd like me to test on my side; otherwise, looks like can be closed. Thanks for your help.

**Comment by eigilnikolajsen** [comment]
Thank you for testing. I'm closing it.
