### ISSUE TITLE
[Request] Hinted TTF versions

### ISSUE THREAD

**Issue by AkshayChn** [eigilnikolajsen/commit-mono#29]
The otf version of the font font looks hazy on 1366x768 displays. Please consider releasing a hinted ttf version.

**Comment by eigilnikolajsen** [comment]
I do want to. I just don't have the time or the skill to do so.

**Comment by rben01** [comment]
Would something like https://freetype.org/ttfautohint/ get most of the way there?

**Comment by Zorbn** [comment]
I tried using ttfautohint on the ttf version from "/src/fonts/..." and it made a big difference on my 1920x1080 monitor. IMO it looked best using "-a sss" for strong hinting.

**Comment by eigilnikolajsen** [comment]
Thank you, I will give this a try. Problem is though that I use [OpenType.js](https://github.com/opentypejs/opentype.js) to generate custom font files on the website, and it can only output .otf files. That best solution I can see is to include autohinted .ttf files in the release here on GitHub. Those files would be with default settings though.
What do you think about this?

**Comment by AkshayChn** [comment]
The default is pretty good as is. An auto hinted ttf version of it is a great start.

**Comment by dajeed** [comment]
I agree with @AkshayChn, the OTF version makes the font look blurry in Visual Studio, but not in Visual Studio Code. I'll post screenshots when I get on my PC
@eigilnikolajsen the default settings as a TTF would be fine! 😄

**Comment by dajeed** [comment]
Visual Studio Code 15px font
![Vscode CommitMono](https://github.com/eigilnikolajsen/commit-mono/assets/8452880/40558922-9944-4ebc-a3f4-35812025b976)

Visual Studio 11px font
![Visual Studio CommitMono](https://github.com/eigilnikolajsen/commit-mono/assets/8452880/a4020b23-82b7-4174-b8a3-af33dcb2c03d)

**Comment by Zorbn** [comment]
> Thank you, I will give this a try. Problem is though that I use [OpenType.js](https://github.com/opentypejs/opentype.js) to generate custom font files on the website, and it can only output .otf files. That best solution I can see is to include autohinted .ttf files in the release here on GitHub. Those files would be with default settings though. What do you think about this?

That sounds like it would be a big improvement, personally I like the default settings and I assume most people are fine with them. It would be a nice option to have.

**Comment by eigilnikolajsen** [comment]
Okay, I hope some of you can help me develop this option, so it is as good as possible.
So if you mind checking these files, it'd help me a lot. In this folder [CommitMonoV136-hinting-test.zip](https://github.com/eigilnikolajsen/commit-mono/files/12558751/CommitMonoV136-hinting-test.zip) I have put files default ttf files with:
- No hinting
- Fontlab's build in hinting
- ttfautohinted (with `-a sss` as the only setting)

What version work best, or ff you have suggestions on how to improve, please tell me!

**Comment by glebd** [comment]
Tested on Windows 10 and HiDPI display in Notepad++ and Sublime Text 3. The autohinted version is much better than Fontlab-hinted, which produced uneven character shapes and thickness. The autohinted version is pretty decent actually.

**Comment by eigilnikolajsen** [comment]
Great to hear!

**Comment by Zorbn** [comment]
I agree that the ttfautohint version is best, tested on Windows 11.

**Comment by AkshayChn** [comment]
The ttfautohinted version is fantastic. Thanks!
System: Ubuntu 22.04, Res: 1366x768.

**Comment by glebd** [comment]
The only issue with the hinted fonts was that the italic version was showing up as a separate font, and so the regular version didn't have italics. Some font naming issue perhaps? But I reckon that was just because of the test nature of the font...

**Comment by eigilnikolajsen** [comment]
I have now added ttfautohinted versions of Commit Mono to [the latest release](https://github.com/eigilnikolajsen/commit-mono/releases/tag/1.136) (and will be added to all future releases). Thank all for your help, I hope you enjoy it!

**Comment by elshize** [comment]
Great stuff! I'm testing the hinted version on Linux and it really makes a huge difference to me. Thanks @eigilnikolajsen and everyone involved!
