### ISSUE TITLE
Latest version messed up line height/vertical positioning?

### ISSUE THREAD

**Issue by rben01** [eigilnikolajsen/commit-mono#30]
In the latest version, line height seems to be totally messed up.

## macOS Terminal.app
Line height = 1:
<img width="842" alt="image" src="https://github.com/eigilnikolajsen/commit-mono/assets/766670/f2046f05-a55b-4774-be1c-3bba0cb479dd">

Line height = 1.5 looks fine, but is the max line height that Terminal.app can do.

## VSCode editor
Line height = 1
<img width="326" alt="image" src="https://github.com/eigilnikolajsen/commit-mono/assets/766670/6d3e75bf-1990-4ffc-b4af-68df0e46f078">

Line height = 1.5:
<img width="317" alt="image" src="https://github.com/eigilnikolajsen/commit-mono/assets/766670/8da89ff9-2dec-4f17-84bb-e5853fc921f7">

## VSCode terminal
Line height = 1:
<img width="1051" alt="image" src="https://github.com/eigilnikolajsen/commit-mono/assets/766670/b815fbbd-cbe7-46cc-aada-965d0b2bc05e">

Line height = 2:
<img width="1045" alt="image" src="https://github.com/eigilnikolajsen/commit-mono/assets/766670/88ea20cc-1ddc-43f0-8553-12ceaeff49bf">

**Comment by eigilnikolajsen** [comment]
This is very curious, thank you for discovering. I have trouble replicating the results, it looks fine in my apps. 
I suppose you downloaded the fonts from the customize section, do you mind sharing the settings (and if you have any other settings that might have something to say)?
It would also be helpful to have a look at the font files, if you can share them here. Thank you.

**Comment by rben01** [comment]
These were downloaded directly from the “Download custom for design” link (using Brave Browser, in case that makes s difference). Here are the files:  [CommitMono.zip](https://github.com/eigilnikolajsen/commit-mono/files/12344947/CommitMono.zip)

One more datapoint: macOS font book install dialog.

Old version of font:
<img width="612" alt="C1B93C06-6E25-4680-94D0-9C9564726496" src="https://github.com/eigilnikolajsen/commit-mono/assets/766670/a338f674-8e72-4cef-9345-89cbe26d5fec">

New version of font:
<img width="612" alt="FDF75E4A-15C0-450F-B851-9DF8F08E31B0" src="https://github.com/eigilnikolajsen/commit-mono/assets/766670/35d8241d-689f-44ed-ae4b-bbfcb4c38eb0">

**Comment by eigilnikolajsen** [comment]
Thank you, I'll have a look at it and fix it as soon as possible!

**Comment by fayekydee** [comment]
Hello,

I can confirm a line spacing issue. In my case the overlap between lines is even more severe - see screenshot of konsole in Debian linux. I have downloaded commit mono today from the commitmono.com customize section.

![commit_line_spacing](https://github.com/eigilnikolajsen/commit-mono/assets/141056929/0fbb57ca-e5ef-4942-bc14-ac464be2369b)

**Comment by eigilnikolajsen** [comment]
It is fixed now. I accidently set the default line height to 0 and not 1, which resulted in really weird vertical metrics. Everything should be normal now.

**Comment by Steve-OH** [comment]
On a related note, the default line height spacing is _very_ tight. Here's what Commit Mono, Fira Code (fairly typical), and MonoLisa (looser than average) look like in Sublime Text on Win10:
![image](https://github.com/eigilnikolajsen/commit-mono/assets/612027/ef6949bb-f484-4723-a163-33c574357e65)

This is with the 1.134 update.
