### ISSUE TITLE
please make the lowercase pqdb more distinct

### ISSUE THREAD

**Issue by bartvdo** [eigilnikolajsen/commit-mono#37]
The lowercase pqdb are mirrors of each other. This makes it harder for dyslexics to pick up differences between the d and b.

**Comment by eigilnikolajsen** [comment]
Those letters are mirrors of each other in almost all fonts. What changes do you propose to combat this?

**Comment by bartvdo** [comment]
Yes, in most fonts they are the same, but I can raise an issue here ;-) .My son is very good in swapping d and b for example. Making them a bit more distinct helps.  If you look at the franklin Gothic example you see that the b and the q have a triangle on the short stalk instead of a square. Other options i have seen is to have the round part start differenly or be less rounded more oval shaped. And the q might have a very small uptick at the end of the downwards stalk. 

I'm not a designer, but it's like the 1l|L thing were you need to make small but obvious changes to differentiate.  

b and q could be a mirror and d and p, because those are dissimilar enough. Maybe for keeping it clean start with doing it like the Gothic example. I suggest to play with it a bit. 

by the way, thanks for looking into this!

**Comment by rben01** [comment]
An idea for distinguishing between them: https://fonts.google.com/specimen/Atkinson+Hyperlegible?preview.text=bdpq&preview.text_type=custom

The b is normal, the d has a slight “tail”, and q has an extreme tail. (p and b are still mirrors of each other though.)

**Comment by glebd** [comment]
If you choose to do this can you do it as a stylistic set/customization option, and keep the main font as neutral and 'character-less' as possible?

**Comment by eigilnikolajsen** [comment]
I've thought about this issue and I won't be fixing it, sorry. The reason is concept of the font; it's supposed to be as neutral as possible, so adding more detail is against its ethos. If you really want these characters to be more distinct, I suggest using a different font. I want Commit Mono to be for everyone, but that's not possible.
