### ISSUE TITLE
Add settings to customized archive

### ISSUE THREAD

**Issue by haarp** [eigilnikolajsen/commit-mono#38]
Hey,

great font! One little detail tho, it would be great if the downloadable archive for the customized font included a (text) document detailing the settings that were used to generate it. For reference, or in case you want to change a setting later on.

Thanks!

**Comment by eigilnikolajsen** [comment]
Awesome idea! Don't know why I didn't think of this:)

**Comment by eigilnikolajsen** [comment]
This is added in the [latest version](https://github.com/eigilnikolajsen/commit-mono/releases/tag/1.136)!
When you download the font, there is a `custom-settings.json` file that contains the custom settings from that download. Click the `Retrieve custom settings` button in 07 Customize on the website and upload the `custom-settings.json` file to input the settings from that version.

**Comment by haarp** [comment]
Yay, this works perfectly. Thanks!
