### ISSUE TITLE
Smart case not perfectly smart

### ISSUE THREAD

**Issue by haarp** [eigilnikolajsen/commit-mono#39]
Hey,

I found an interesting issue that is reproducible on the commitmono.com page.

- Go to Customize
- Select C++ as example
- Toggle Smart case

- Observe `1][0]`: Both `[` and `]` are raised.
- Observe `argv[1];`: Only `]` is raised, leading to inconsistency.

So it seems Smart case doesn't react properly when bordered by letters.

Cheers!

**Comment by eigilnikolajsen** [comment]
Good call!
This is actually due to the fact that the `v` next to `[` is lowercase where as `;` is neutral.
I will try to add some logic so this doesn't happen.

**Comment by eigilnikolajsen** [comment]
This should be fixed in the [latest release](https://github.com/eigilnikolajsen/commit-mono/releases/tag/1.136). However, I have a feeling that there could be more issues out there, so I will try to fine tune it again later.

**Comment by haarp** [comment]
Thanks. However something seems to be broken now, rendering went bonkers in my text editor (xed) using a custom version.

Screenshot: 
![Screenshot_2023-09-07_11-25-30](https://github.com/eigilnikolajsen/commit-mono/assets/781030/f1848639-d090-4672-a44f-3f7ba7271e55)

Settings
[CommitMono_custom-settings.json.zip](https://github.com/eigilnikolajsen/commit-mono/files/12547169/CommitMono_custom-settings.json.zip)

**Comment by eigilnikolajsen** [comment]
That looks super weird. When I download the font with the custom settings you attached, I see nothing wrong with them. Can you send your font files, so I can check them?

**Comment by haarp** [comment]
Wait, it seems the problem was my editor. It seems to dislike replacing font files while it's running. Looks fine after restarting it.

As for Smart Case: Judging by the website, it now doesn't modify `[` or `]` at any location in the C++ example. Consistency :)

I notice something in the Python example however. In `% 2 == 0 and` the `==` gets raised, `(x == 1):` it's not.

**Comment by eigilnikolajsen** [comment]
Okay, case closed haha.
The Python example is intentional. Since `x` is lowercase the `==` follows its case rather than the case of `1`.

**Comment by haarp** [comment]
Ah, gotcha. Thanks for your time and thanks for making this font!

**Comment by nmsmith** [comment]
The smart casing for brackets/parens/braces is still very clunky, IMO. It's easy to end up with a pair of brackets that are vertically misaligned. If the brackets are close together, this misalignment is noticeable.

It could be worthwhile splitting the smart case feature into two parts:
1. Smart case for brackets
2. Smart case for "everything else"

IMO, only the latter feature should be selected by default on the website, because it is only one that is robust.
