### ISSUE TITLE
Thicker font weight

### ISSUE THREAD

**Issue by rben01** [eigilnikolajsen/commit-mono#43]
The 400 font weight, the “normal” weight, is quite thin. Commit Mono’s site advises to use the 450 or 500 weights.

This strikes me as odd. Shouldn't the default weight “just work”? Having to pick the font weight to get a reasonable weight is inconvenient and in some cases impossible (e.g., VS Code lets you choose the font, but not the weight, of the text in the git commit message text field).

I think 400 should be made thicker so that it's suitable as the default weight (probably what 475 is now), with the other weights adjusted accordingly.

**Comment by eigilnikolajsen** [comment]
Thank you for the feedback, I will consider taking action to make the default 400 a bit thicker.

**Comment by eigilnikolajsen** [comment]
This is resolved in [this release](https://github.com/eigilnikolajsen/commit-mono/releases/tag/1.137)!
