### ISSUE TITLE
Extra files in released zip package for 1.137

### ISSUE THREAD

**Issue by shurizzle** [eigilnikolajsen/commit-mono#46]
<img width="522" alt="immagine" src="https://github.com/eigilnikolajsen/commit-mono/assets/203655/9867d43b-5c9d-4332-9d82-7eb97cfbd129">
Something went wrong in the release I guess, I see an extra `ttfautohint` directory and a `CommitMono.zip`.

**Comment by eigilnikolajsen** [comment]
The CommitMono.zip is wrong, that is fixed now, thank you. But the ttfautohint folder was added in the previous release because of [this issue](https://github.com/eigilnikolajsen/commit-mono/issues/29).

**Comment by shurizzle** [comment]
I don't want to open another issue for this, but: I'm maintaining the aur package (https://aur.archlinux.org/packages/otf-commit-mono). It's difficult to keep track of changes if you change the released zip file because github do not notify me. I noticed in this moment that 1.336 is broken because the checksum is changed and the directory tree in the zip is completely different. Can you keep the releases untouched and create minor releases instead? (1.336.1, 1.336.2, 1.336.3, etc)

**Comment by eigilnikolajsen** [comment]
Thank you, I think I understand. I will do that in the future!

**Comment by eigilnikolajsen** [comment]
Do you need me to do anything right now?

**Comment by shurizzle** [comment]
No, that's all good. Thank you for you work 😄
