### ISSUE TITLE
Incorrect tracking of italic 9

### ISSUE THREAD

**Issue by rben01** [eigilnikolajsen/commit-mono#48]
This is in release 1.137. See attached screenshot.

<img width="1129" alt="BDA2D430-AA11-46B7-BA20-33BB2A99D3DF" src="https://github.com/eigilnikolajsen/commit-mono/assets/766670/1079ccaa-deaa-4052-aad7-583f20d2492b">

**Comment by eigilnikolajsen** [comment]
Thank you. I will fix this first priority.

**Comment by eigilnikolajsen** [comment]
Fixed in [release 1.138](https://github.com/eigilnikolajsen/commit-mono/releases/tag/1.138).
