### ISSUE TITLE
Issue in Microsoft Word and Office Email

### ISSUE THREAD

**Issue by eigilnikolajsen** [eigilnikolajsen/commit-mono#49]
I've heard there might be problems in this software. I need someone to post screenshots of how the font looks.

**Comment by LGruenfeld** [comment]
[CommitMono-Screenshots.docx](https://github.com/eigilnikolajsen/commit-mono/files/12641578/CommitMono-Screenshots.docx)

I hope the attached is self-explanatory as to how the font appears in several of my Windows apps. Notepad, PowerPoint and Excel are all fine; Word and Outlook email, not so much.

Thanks, Eigil.

-lee gruenfeld
www.leegruenfeld.com

**Comment by eigilnikolajsen** [comment]
![image015](https://github.com/eigilnikolajsen/commit-mono/assets/71004327/ac4edb0b-ea57-4a58-aa67-aa289346b0e3)
![image010](https://github.com/eigilnikolajsen/commit-mono/assets/71004327/d047a46e-ae1c-4ffe-9a5e-f7c7f58dc5e9)
![image008](https://github.com/eigilnikolajsen/commit-mono/assets/71004327/b40a3f6e-e246-4853-88b4-b58a966984f2)
![image005](https://github.com/eigilnikolajsen/commit-mono/assets/71004327/d65c904e-55a6-466a-b1cf-bc683735f2e4)

**Comment by eigilnikolajsen** [comment]
These were the supplied images. It seems to me that you @LGruenfeld just have to pick the 'regular' and not the 'bold' version of the font. So when picking the fonts; don't use bold just use regular. When trying to replicate the issue in Microsoft Word, I get no issues. 

However, in order to use the 'Smart Kerning' feature of Commit Mono you have to enable contextual alternates. To do this in Word, you have to go to Format -> Font -> Advanced -> check the box 'Use contextual alternates'
Hope this helpes.
