### ISSUE TITLE
Website is intentionally shitty

### ISSUE THREAD

**Issue by albedoa** [eigilnikolajsen/commit-mono#5]

**Comment by mmlb** [comment]
The issue feels pretty useless as-is so I'll add something useful. Having simple download links would be fantastic to have so the font can be more easily packaged up for linux distros.

**Comment by eigilnikolajsen** [comment]
Yes, I will look into making a release with a non-customized standard version of the font.

**Comment by braver** [comment]
@eigilnikolajsen love the site 👍🏻 Good to see some creativity every now and then.

**Comment by rossburton** [comment]
A big improvement would be a download link that is an `<a>` so packagers don't need to dig through the source.
