### ISSUE TITLE
Unable to download font using Firefox

### ISSUE THREAD

**Issue by KaranAhlawat** [eigilnikolajsen/commit-mono#51]
If I customize the font, and then hit the "Download custom for dev" link, it gives me an `X`. Checking the console logs, this appears to be due to a missing function or the like.

![image](https://github.com/eigilnikolajsen/commit-mono/assets/56113511/29cf45c3-e49a-497d-b4d5-058e83134c1c)

**Comment by eigilnikolajsen** [comment]
Are you using Safari? It seems to work for me, so it would help if you provide more info on your system, and the settings you're downloading with.

**Comment by KaranAhlawat** [comment]
I'm on Firefox 102.

The customizations are as follows

```json
{"weight":400,"italic":false,"alternates":{"cv01":true,"cv02":false,"cv03":false,"cv04":true,"cv05":false,"cv06":false,"cv07":false,"cv08":true,"cv09":false},"features":{"ss01":false,"ss02":false,"ss03":true,"ss04":true,"ss05":true},"letterSpacing":0,"lineHeight":1,"fontName":"Alt"}
```

If there is some other information you think would help out, please let me know.

**Comment by eigilnikolajsen** [comment]
Thank you, this is now [fixed](https://github.com/eigilnikolajsen/commit-mono/pull/52). Please try again, you should be successful!
