### ISSUE TITLE
Separate out italics in variable font

### ISSUE THREAD

**Issue by rben01** [eigilnikolajsen/commit-mono#53]
The `ital` axis is notoriously tricky to work with in browsers (depending on the browser, it requires `font-synthesis: 1` and/or `font-variation-settings: "ital" 1`). It'd be handy to have the `ital = 1` version of the variable font split out into a separate file for ease of use in browsers.

**Comment by eigilnikolajsen** [comment]
The purpose of the variable font is to have it all in one file. I won't be changing this at the moment. I will consider it if it's a wish from multiple people.

Consider loading the font with 2 different `@font-face`s if you can't make `font-variation-settings: "ital" 1` work.

**Comment by rben01** [comment]
Ok. In the meantime I will subset manually using this: https://fonttools.readthedocs.io/en/latest/_modules/fontTools/varLib/instancer.html
