### ISSUE TITLE
Enabling cv03 breaks ss01

### ISSUE THREAD

**Issue by samgaw** [eigilnikolajsen/commit-mono#55]
Enabling `cv03 on` appears to break some ligatures.

![47EFBBDB-94CE-4940-848F-1225CBB94292_1_201_a](https://github.com/eigilnikolajsen/commit-mono/assets/57853/e614ed8c-2352-4c65-8795-895308498e18)

**Comment by eigilnikolajsen** [comment]
You are completely right. Thank you!

**Comment by eigilnikolajsen** [comment]
This is fixed in the [latest release](https://github.com/eigilnikolajsen/commit-mono/releases/tag/v1.140)
