### ISSUE TITLE
Can not use this font in Postico

### ISSUE THREAD

**Issue by sergeysolovev** [eigilnikolajsen/commit-mono#58]
Postico app uses the following dialog for picking a font

<img width="778" alt="Screenshot 2023-10-07 at 1 36 08 AM" src="https://github.com/eigilnikolajsen/commit-mono/assets/5831301/4cbfb2c5-c402-49b8-9166-5fac60771ee1">

Somehow “Commit Mono” didn’t make it there, I’m wondering if there is some flag that got to be set to explicitly make it “fixed width” category.

**Comment by eigilnikolajsen** [comment]
I am aware of the issue. It's actually a bug in OpenType.js which is a library I'm using to generate the fonts on the web. Refer to [this issue](https://github.com/eigilnikolajsen/commit-mono/issues/15) for future updates.

I'm closing this, as it is a duplicate.

**Comment by sergeysolovev** [comment]
@eigilnikolajsen Thank you sir
