### ISSUE TITLE
Kerning is off by default in some software

### ISSUE THREAD

**Issue by sergeysolovev** [eigilnikolajsen/commit-mono#60]
Hello, is it possible to make kerning on by default like it’s done for many other fonts?
For example, in VSCode, if the setting `"editor.fontLigatures"` is not set, the kerning would be off. So things like `mm` would look a bit off. In VSCode terminal there is no way to activate ligatures at all, so kerning would be off. Same is true for iTerm.app.

I tried to download custom build with `ss05` on, but still no effect.

**Comment by eigilnikolajsen** [comment]
Unfortunately, this is not about font files – it is up to text software to enable ligatures. Most terminals don't support ligatures at all, but there's really nothing the font can do about it. Sorry, I'm closing this.
