### ISSUE TITLE
Suggestion: add an alternative version of lowercase "L"

### ISSUE THREAD

**Issue by aabbccddeeffggj** [eigilnikolajsen/commit-mono#61]
Hi; firstly, I would like to praise you for the font you produced, certainly the best one I've come across, both due to its consistency/quality and effort in the customization of it.
The suggestion I have in mind is: add a variant to the lowercase "L" character in the customization possibilities, here is the variant format I'm referring to:
![image](https://github.com/eigilnikolajsen/commit-mono/assets/133555950/b4b95e24-7797-49c4-b035-3a62d857aa63)

**Comment by eigilnikolajsen** [comment]
Good idea, I've thought of this before, but not sure if anyone wanted it. Will probably add it soon, since it's fairly easy to implement.

**Comment by eigilnikolajsen** [comment]
This has been added in the [latest release](https://github.com/eigilnikolajsen/commit-mono/releases/tag/v1.140)

**Comment by aabbccddeeffggj** [comment]
> This has been added in the [latest release](https://github.com/eigilnikolajsen/commit-mono/releases/tag/v1.140)

Great! Thanks a lot!

**Comment by aabbccddeeffggj** [comment]
I think the site needs updating, when I choose the alternative 'L' in the customization section, it fails to download.

**Comment by eigilnikolajsen** [comment]
Odd issue, that I did not see coming. It's working now! Head on over and get your custom `l`!
