### ISSUE TITLE
Missing underline values in 'post' table

### ISSUE THREAD

**Issue by userNeptune** [eigilnikolajsen/commit-mono#62]
![post_table](https://github.com/eigilnikolajsen/commit-mono/assets/29615651/4e246afb-f8bc-4011-b999-b447ee8de6af)

Maybe is related: #10

**Comment by eigilnikolajsen** [comment]
There's a fix on the way! This issue is indeed related to both #10 as well as #15 
Hopefully they'll all be resolved by the next release.

**Comment by eigilnikolajsen** [comment]
Should be fixed in the [latest release](https://github.com/eigilnikolajsen/commit-mono/releases/tag/v1.140)
