### ISSUE TITLE
Wrong render in Visual Studio 2022 at 100% zoom

### ISSUE THREAD

**Issue by gbellini79** [eigilnikolajsen/commit-mono#66]
At 100% zoom the font is rendered wrong:
![image](https://github.com/eigilnikolajsen/commit-mono/assets/20949424/fb040010-eafb-4852-98bb-a7f8a5e3c4a5)

At any other zoom level it seems to be correct:
110%
![image](https://github.com/eigilnikolajsen/commit-mono/assets/20949424/c0c7542f-c855-41d0-9c02-5c98a9df019a)

91%
![image](https://github.com/eigilnikolajsen/commit-mono/assets/20949424/b214bcc7-afdb-469a-a8ca-ba48c966b563)

Is this a CommitMono or Visual Studio issue?
Since I haven't found a real solution yet, the workaround is to decrease the font size and keep the zoom level at 110%.
Thank you in advance.

**Comment by eigilnikolajsen** [comment]
Can you provide some context? Are you using Windows, and is it the .ttf files?

**Comment by gbellini79** [comment]
Yes, Windows and .ttf files from the GitHub package version v1.141.
I tried to remove and reinstall all the CommitMono fonts and now it seems a completely different font is rendered:
![image](https://github.com/eigilnikolajsen/commit-mono/assets/20949424/cd4abd72-a463-4861-b052-7143ffcd4c19)

**Comment by eigilnikolajsen** [comment]
Very weird issue, I'm not sure how to replicate this.

**Comment by gbellini79** [comment]
It looks like it was a Visual Studio bug: https://developercommunity.visualstudio.com/t/Custom-fonts-ignored-in-VS2022-code-wind/10514561

Thank you for your time

**Comment by eigilnikolajsen** [comment]
Thank you for the update.
