### ISSUE TITLE
May I ask how to fill in the name of the font in the software?

### ISSUE THREAD

**Issue by vagreargnatry** [eigilnikolajsen/commit-mono#68]
Sorry, I forgot when I used to fill in the font name with 'CommitMono'. This can be used in both VS Code and Alacritty. In `v1.141`, this method didn't work in my computer (Windows 11).
Now, I can use `CommitMono 400 Regular` for VS Code. But for Alacritty, I don't know how to fill the name.

![image](https://github.com/eigilnikolajsen/commit-mono/assets/104709852/4a5acaef-bc1d-4f07-bcc9-cf7b00b2be47)

**Comment by eigilnikolajsen** [comment]
That's a bit weird. It should work with just "CommitMono". It's difficult for me to test since Windows and OSX treat font naming differently. I'll do my best to fix this.
In the meantime you can try adding hyphens: "CommitMono-Regular", "CommitMono-400", "CommitMono-400-Regular" but it's merely a shot in the dark.

**Comment by eigilnikolajsen** [comment]
This will be fixed when #70 is. Will keep you updated.

**Comment by vagreargnatry** [comment]
Hello! Thank you for your efforts. The issue still persists on my computer with version 1.142. In VS Code, using `CommitMono 400 Regular` works, but using `CommitMono` doesn't take effect. In version 1.141, the four font styles in the Windows 11 settings interface are together. However, in version 1.142, the italic and non-italic styles are separated.

![image](https://github.com/eigilnikolajsen/commit-mono/assets/104709852/d6d77258-b377-49cc-80c8-009b5b9cb031)

![image](https://github.com/eigilnikolajsen/commit-mono/assets/104709852/611009f5-60b3-4c9b-89d5-120d98f3c4f6)

![image](https://github.com/eigilnikolajsen/commit-mono/assets/104709852/e0c2aa1b-8066-407f-ac63-a3444c312105)

![image](https://github.com/eigilnikolajsen/commit-mono/assets/104709852/d7a45aa2-dfc7-4a86-9b72-157dd6b86542)

**Comment by vagreargnatry** [comment]
Hello. If I only use https://github.com/eigilnikolajsen/commit-mono/blob/main/src/fonts/fontlab/CommitMonoV142-VF.ttf, there are 42 fonts on my computer. At this point, entering "CommitMonoV142" in VS Code allows for normal usage. Please see the following image.

![image](https://github.com/eigilnikolajsen/commit-mono/assets/104709852/6fe800ac-38b2-4c64-9ad2-53ad02650325)

![image](https://github.com/eigilnikolajsen/commit-mono/assets/104709852/a350e89a-9bff-4ff6-9295-01e93f3d663b)

![image](https://github.com/eigilnikolajsen/commit-mono/assets/104709852/6bb5c32f-fe0b-4c5f-b49b-d4ccf26a59ca)

If I install it first and then install the fonts downloaded from the official website, there will be two categories, with a total of 44 fonts in one category and 2 fonts in the other.

![image](https://github.com/eigilnikolajsen/commit-mono/assets/104709852/3254f96d-29ea-4c4a-ad75-a12670c54281)

![image](https://github.com/eigilnikolajsen/commit-mono/assets/104709852/9be35c1a-f73a-45e2-9b4c-55908cbfa227)

**Comment by eigilnikolajsen** [comment]
I think I've resolved the issue with the latest website update. You may try to download the latest version from the website, and tell me if it works with just "CommitMono". Thank you!

**Comment by vagreargnatry** [comment]
The latest version from the website works with just "CommitMono" In VS Code and Alacritty. Thank you so much!

![image](https://github.com/eigilnikolajsen/commit-mono/assets/104709852/12b5037c-d38e-4dd3-a2ad-af942a524497)

**Comment by vagreargnatry** [comment]
And on my computer's control panel, v1.142 shows `CommitMono Bold` and `CommitMono Italic`.

![image](https://github.com/eigilnikolajsen/commit-mono/assets/104709852/45a1fb29-22e3-48f9-a933-941daaaa50ab)

It shows four kinds of fonts in Windows 11 settings.

![image](https://github.com/eigilnikolajsen/commit-mono/assets/104709852/2475ee8b-c364-40a4-be36-619f6936098d)

![image](https://github.com/eigilnikolajsen/commit-mono/assets/104709852/5ebf26e0-a451-4c8a-939e-5b0b408e2ad2)

**Comment by vagreargnatry** [comment]
Hello! After some computer restarts, I see "CommitMono Bold Italic" and "CommitMono Italic" in my control panel. In Microsoft Word, only "CommitMono" is available as a font option, and when selected, the font appears in italics. This behavior is also present in v1.139.

![image](https://github.com/eigilnikolajsen/commit-mono/assets/104709852/23f0b9c4-71ed-42d9-a50e-cb48686b95bc)

![image](https://github.com/eigilnikolajsen/commit-mono/assets/104709852/97d3d569-9579-4626-b931-f4f6aeecd52d)

I believe Microsoft Word is not well-suited for displaying these monospaced fonts. On my computer's Microsoft Word, certain fonts like "Rec Mono Linear" only appear as a single option (unlike CommitMono, it doesn't default to italics). For fonts like "Cascadia Mono," there are many options displayed, but you cannot select italics directly here; instead, it must be done by marking that portion of the text as italic in Microsoft Word. Meanwhile, fonts like "Iosevka" show numerous choices, allowing direct selection of italics, even if Microsoft Word hasn't marked that segment of text as italic.

![image](https://github.com/eigilnikolajsen/commit-mono/assets/104709852/3d4c6d29-f5db-4066-b8b6-115f7eda0469)

![image](https://github.com/eigilnikolajsen/commit-mono/assets/104709852/e54fb074-372a-42a8-8085-e671a06f9516)

![image](https://github.com/eigilnikolajsen/commit-mono/assets/104709852/a912b17c-7851-4617-98ef-9a2744f84979)

**Comment by eigilnikolajsen** [comment]
Font naming for Office Programs is really a whole different topic, and often requires a different font file all together to work properly. It is not a priority for Commit Mono to work in Word, but I will do my best to resolve the matter in the future.

However, I am closing this issue since it is resolved with [release v1.142](https://github.com/eigilnikolajsen/commit-mono/releases/tag/v1.142). If you think the Office Word is important, I encourage you to open a different issue. Thank you.
