### ISSUE TITLE
Can't zoom out

### ISSUE THREAD

**Issue by miiichael** [eigilnikolajsen/commit-mono#7]
Pressing `-` zooms in rather than out, and pressing `+` (or `=`) does nothing. \*reads nav.js* Ohh, zoom out is bound to `/`! It would be nice if the keypad `+`/`-` worked too, if only so that us US layout users will be less likely to complain. 😅

(Both the font and website are great BTW)

**Comment by eigilnikolajsen** [comment]
Great idea, I didn't think of that. I will update to include keypad `+` & `-`.

**Comment by eigilnikolajsen** [comment]
@miiichael It should be fixed now.
