### ISSUE TITLE
Alternate symbol for 1 (one)

### ISSUE THREAD

**Issue by nikola-vukicevic** [eigilnikolajsen/commit-mono#71]
Would you consider providing an alternate symbol for the numerical digit 1 (one)?

Something plain.

And here's the reason why I'm asking ....

On the one hand, the "super normal manifesto" on your site really makes sense (and should resonate with anyone who really cares about design), but then, there's the "1" with the "carved" top-left that just "quietly screams" - "I am special".

(For some reason, it really draws attention to itself.)

In all honesty, I'm saying all of this because I feel you have (otherwise) done a pretty great job with the font. :)

Best regards

**Comment by eigilnikolajsen** [comment]
Thank you! I am happy to discuss this. 
The reason the `1` is drawn this particular way is mainly twofold. Firstly, I have taken much inspiration in the font Helvetica, which uses this design. Helvetica (and Arial) are considered pretty normal in design. Secondly, it's a high priority in coding fonts the common glyphs are differentiated so can easily tell the difference. The curved top makes a greater difference between `1`, `l` and `7`. 
Can I ask you for an example of the style of the alternative `1` you're seeking?

**Comment by nikola-vukicevic** [comment]
> .... Can I ask you for an example of the style of the alternative `1` you're seeking?

Sure. :)

It's the kind of "1" found in these fonts: Fira Code, JetBrains Mono, Source Code Pro, Cascadia Code, Consolas, Menlo/Meslo, or the one (no pun intended), found on GitHub ATM.

In my humble opinion, a "flat" 1 would provide for a much better differentiation (the "carved" one just doesn't look/feel right when you're viewing code).

**Comment by eigilnikolajsen** [comment]
Thank you! I will most likely add this in the next release.

**Comment by nikola-vukicevic** [comment]
> Thank you! I will most likely add this in the next release.

Thank you, Eigil, that would be really useful.

**Comment by eigilnikolajsen** [comment]
This is in the [latest release](https://github.com/eigilnikolajsen/commit-mono/releases/tag/v1.143)! I liked it so much I made it the default:)
