### ISSUE TITLE
Shorter cv08, handwriting style

### ISSUE THREAD

**Issue by stevemolitor** [eigilnikolajsen/commit-mono#72]
I love this font! It took me some fiddling to get the smart kerning to work with Emacs, but I got that working and now it's my new favorite font. _Very_ readable, and looks great without calling attention to itself.

I like the "cv08: Alt. italic 'aefgy'" feature. It helps make italics stand out a bit. 

The cv08 "f" is very long-legged though. It sticks out - not "anonymous" at all! Would it be possible to shorten the "f" in cv08? 

Also, a handwriting or script variant would be super cool.

**Comment by stevemolitor** [comment]
Maybe if instead of jutting down the f leg curved to the left at the bottom it would soften the effect and be consistent with the curvy tails  of the g and y.

**Comment by eigilnikolajsen** [comment]
Good ideas, I will add this to the next release!

**Comment by stevemolitor** [comment]
Awesome thanks!

**Comment by eigilnikolajsen** [comment]
I have added a curve legged italic `f` in the [latest release](https://github.com/eigilnikolajsen/commit-mono/releases/tag/v1.143) tell me what you think @stevemolitor

**Comment by stevemolitor** [comment]
Hi sorry for the delayed response. I was on my honeymoon and wasn’t thinking much about fonts :) .The curvey f looks great! Thanks so much!The smart kerning seems even nicer now as well. SteveOn Dec 28, 2023, at 3:14 AM, Eigil Nikolajsen ***@***.***> wrote:﻿
I have added a curve legged italic f in the latest release tell me what you think @stevemolitor

**Comment by eigilnikolajsen** [comment]
Awesome, thank you! I'm closing this one.
