### ISSUE TITLE
"COUNT" is made worse by kerning

### ISSUE THREAD

**Issue by awelotta** [eigilnikolajsen/commit-mono#77]
I think O U and N should have the same width.

COUNT
(−kerning):
![image](https://github.com/eigilnikolajsen/commit-mono/assets/74327187/41170898-adb3-494a-b767-80a50ac544d7)

(+kerning):
![image](https://github.com/eigilnikolajsen/commit-mono/assets/74327187/b69b327a-9276-4ed8-a243-63350836dc21)

"OU" are already a little too close; and turning kerning on brings "OU" even closer together.

I don't think this would negatively affect "N" in other contexts. Example (+kerning)
![image](https://github.com/eigilnikolajsen/commit-mono/assets/74327187/5a32abf9-8fb8-4d06-8e8a-f82a21b0b0c1)
I think the "o" in "Noi" could be shifted to the same position as in "Uoi" without ill effect.

There's probably other letters whose width classes should be reclassified; perhaps "V" should be in the normal class same as "FJPTY"?
![image](https://github.com/eigilnikolajsen/commit-mono/assets/74327187/ebf89774-5fa2-4422-8f68-71dc4c302f45)
("Voi" but with "o" positioned as if it were in "Toi").

**Comment by eigilnikolajsen** [comment]
You're right. I will have a look at these.

**Comment by eigilnikolajsen** [comment]
The suggested changes have been made in the [latest release](https://github.com/eigilnikolajsen/commit-mono/releases/tag/v1.143). I think it's better the way you proposed, thank you!:)
