### ISSUE TITLE
æ and œ should be wider, maybe

### ISSUE THREAD

**Issue by awelotta** [eigilnikolajsen/commit-mono#78]
```
mbi
æbi
œbi
```
renders with kerning as
![image](https://github.com/eigilnikolajsen/commit-mono/assets/74327187/7726d420-6d09-462f-a5da-72d2fb330161)

I'm guessing the glyphs themselves can't be made wider without risking a sequence like `æmm` being too tight. But I think æ and œ  should be in the same width class as `w` and `m`.

**Comment by eigilnikolajsen** [comment]
These are not in the kerning classes for the same reason as the diacritis, as described in my comment in #76 
For this reason I'm closing this issue, reopen if you think this is a mistake.
