### ISSUE TITLE
should whitespace be treated as "narrow" letter class? for kerning

### ISSUE THREAD

**Issue by awelotta** [eigilnikolajsen/commit-mono#79]
I think it might make more sense to treat whitespace/EOF(? is that possible?) like narrow letters.

```
mmoi
mmo
```
![image](https://github.com/eigilnikolajsen/commit-mono/assets/74327187/be2644b6-49c9-4974-ac1d-8dfa2009afad)

I think the kerning "mmo" in "mmoi" looks more nicely spaced than "mmo" surrounded by whitespace

But other letter combinations seem like they would suffer a little.
```
immi
imm
```
![image](https://github.com/eigilnikolajsen/commit-mono/assets/74327187/5600de14-ce36-4b0e-a1d4-d571ba1a1ba3)
Here, `imm` alone is better than `immi` I feel.

**Comment by eigilnikolajsen** [comment]
Good point. I have already looked at implementing this before, but I didn't do it since the first letter of each line in code looked a little out of place when kerned, but I will have a look again because of this.

**Comment by eigilnikolajsen** [comment]
This is a reality in the [latest release](https://github.com/eigilnikolajsen/commit-mono/releases/tag/v1.143)! I think it's quite awesome actually:)
